// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package store

import (
	"context"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (year) VALUES (?) RETURNING id, year
`

func (q *Queries) CreateChallenge(ctx context.Context, year int64) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, createChallenge, year)
	var i Challenge
	err := row.Scan(&i.ID, &i.Year)
	return i, err
}

const getChallengeByYear = `-- name: GetChallengeByYear :one
SELECT id, year FROM challenges WHERE year = ?
`

func (q *Queries) GetChallengeByYear(ctx context.Context, year int64) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, getChallengeByYear, year)
	var i Challenge
	err := row.Scan(&i.ID, &i.Year)
	return i, err
}

const listChallenges = `-- name: ListChallenges :many
SELECT id, year FROM challenges ORDER BY year DESC
`

func (q *Queries) ListChallenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, listChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Challenge{}
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(&i.ID, &i.Year); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
