// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Challenge struct {
	ID   int64
	Year int64
}

type ChallengeMovie struct {
	ID          int64
	ChallengeID int64
	MovieID     int64
	Position    int64
	WatchedAt   sql.NullString
}

type Movie struct {
	ID          int64
	TmdbID      int64
	Title       string
	ReleaseDate sql.NullString
	PosterPath  sql.NullString
	Overview    sql.NullString
	CreatedAt   string
}

type Rating struct {
	ID               int64
	UserID           int64
	ChallengeMovieID int64
	Score            int64
	UpdatedAt        string
}

type User struct {
	ID          int64
	DisplayName string
	Role        string
	CreatedAt   string
	DisabledAt  sql.NullString
}

type UserToken struct {
	UserID    int64
	TokenHash []byte
	CreatedAt string
}
