// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package store

import (
	"context"
	"database/sql"
)

const getMovieByTMDBID = `-- name: GetMovieByTMDBID :one
SELECT id, tmdb_id, title, release_date, poster_path, overview, created_at FROM movies WHERE tmdb_id = ?
`

func (q *Queries) GetMovieByTMDBID(ctx context.Context, tmdbID int64) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovieByTMDBID, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.ReleaseDate,
		&i.PosterPath,
		&i.Overview,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMovie = `-- name: UpsertMovie :one
INSERT INTO movies (tmdb_id, title, release_date, poster_path, overview)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (tmdb_id) DO UPDATE SET
    title = excluded.title,
    release_date = excluded.release_date,
    poster_path = excluded.poster_path,
    overview = excluded.overview
RETURNING id, tmdb_id, title, release_date, poster_path, overview, created_at
`

type UpsertMovieParams struct {
	TmdbID      int64
	Title       string
	ReleaseDate sql.NullString
	PosterPath  sql.NullString
	Overview    sql.NullString
}

func (q *Queries) UpsertMovie(ctx context.Context, arg UpsertMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, upsertMovie,
		arg.TmdbID,
		arg.Title,
		arg.ReleaseDate,
		arg.PosterPath,
		arg.Overview,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.ReleaseDate,
		&i.PosterPath,
		&i.Overview,
		&i.CreatedAt,
	)
	return i, err
}
