// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package store

import (
	"context"
)

const listChallengeRatings = `-- name: ListChallengeRatings :many
SELECT r.id, r.user_id, r.challenge_movie_id, r.score, r.updated_at,
       u.display_name
FROM ratings AS r
JOIN challenge_movies AS cm ON cm.id = r.challenge_movie_id
JOIN users AS u ON u.id = r.user_id
WHERE cm.challenge_id = ?
ORDER BY cm.position, r.user_id
`

type ListChallengeRatingsRow struct {
	ID               int64
	UserID           int64
	ChallengeMovieID int64
	Score            int64
	UpdatedAt        string
	DisplayName      string
}

func (q *Queries) ListChallengeRatings(ctx context.Context, challengeID int64) ([]ListChallengeRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChallengeRatings, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengeRatingsRow{}
	for rows.Next() {
		var i ListChallengeRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeMovieID,
			&i.Score,
			&i.UpdatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (user_id, challenge_movie_id, score)
SELECT ?1, cm.id, ?2
FROM challenge_movies AS cm
WHERE cm.id = ?3 AND cm.challenge_id = ?4
ON CONFLICT (user_id, challenge_movie_id) DO UPDATE SET
    score = excluded.score,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, challenge_movie_id, score, updated_at
`

type UpsertRatingParams struct {
	UserID           int64
	Score            int64
	ChallengeMovieID int64
	ChallengeID      int64
}

// The caller must derive user_id from the authenticated user, not form input.
// A mismatched entry/challenge returns no rows and cannot update another year.
func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, upsertRating,
		arg.UserID,
		arg.Score,
		arg.ChallengeMovieID,
		arg.ChallengeID,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeMovieID,
		&i.Score,
		&i.UpdatedAt,
	)
	return i, err
}
