// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_tokens.sql

package store

import (
	"context"
	"database/sql"
)

const deleteUserToken = `-- name: DeleteUserToken :exec
DELETE FROM user_tokens WHERE user_id = ?
`

func (q *Queries) DeleteUserToken(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserToken, userID)
	return err
}

const getActiveUserByTokenHash = `-- name: GetActiveUserByTokenHash :one
SELECT u.id, u.display_name, u.role, u.created_at, u.disabled_at FROM users AS u
JOIN user_tokens AS t ON t.user_id = u.id
WHERE t.token_hash = ? AND u.disabled_at IS NULL
`

func (q *Queries) GetActiveUserByTokenHash(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByTokenHash, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT u.id, u.display_name, u.role, u.created_at, u.disabled_at, t.user_id IS NOT NULL AS has_token
FROM users AS u
LEFT JOIN user_tokens AS t ON t.user_id = u.id
ORDER BY CASE u.role WHEN 'owner' THEN 0 ELSE 1 END, u.id
`

type ListManagedUsersRow struct {
	ID          int64
	DisplayName string
	Role        string
	CreatedAt   string
	DisabledAt  sql.NullString
	HasToken    bool
}

func (q *Queries) ListManagedUsers(ctx context.Context) ([]ListManagedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listManagedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedUsersRow{}
	for rows.Next() {
		var i ListManagedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.HasToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserToken = `-- name: SetUserToken :exec
INSERT INTO user_tokens (user_id, token_hash)
VALUES (?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    token_hash = excluded.token_hash,
    created_at = CURRENT_TIMESTAMP
`

type SetUserTokenParams struct {
	UserID    int64
	TokenHash []byte
}

// Never store or return the raw personal login token.
func (q *Queries) SetUserToken(ctx context.Context, arg SetUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, setUserToken, arg.UserID, arg.TokenHash)
	return err
}
