// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name, role)
VALUES (?, ?)
RETURNING id, display_name, role, created_at, disabled_at
`

type CreateUserParams struct {
	DisplayName string
	Role        string
}

// Administration must be authorized by the application before invoking writes.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :one
UPDATE users SET disabled_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, display_name, role, created_at, disabled_at
`

func (q *Queries) DisableUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, disableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const enableUser = `-- name: EnableUser :one
UPDATE users SET disabled_at = NULL WHERE id = ? RETURNING id, display_name, role, created_at, disabled_at
`

func (q *Queries) EnableUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, enableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, role, created_at, disabled_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, role, created_at, disabled_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameUser = `-- name: RenameUser :one
UPDATE users SET display_name = ? WHERE id = ? RETURNING id, display_name, role, created_at, disabled_at
`

type RenameUserParams struct {
	DisplayName string
	ID          int64
}

func (q *Queries) RenameUser(ctx context.Context, arg RenameUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, renameUser, arg.DisplayName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}
