// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package store

import (
	"context"
)

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO user_sessions (session_hash, user_id, token_hash, expires_at, max_expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserSessionParams struct {
	SessionHash  []byte
	UserID       int64
	TokenHash    []byte
	ExpiresAt    int64
	MaxExpiresAt int64
}

// Never store or return the raw session cookie value.
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUserSession,
		arg.SessionHash,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.MaxExpiresAt,
	)
	return err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :exec
DELETE FROM user_sessions WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredUserSessions, now)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions WHERE session_hash = ?
`

func (q *Queries) DeleteUserSession(ctx context.Context, sessionHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteUserSession, sessionHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM user_sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getUserSession = `-- name: GetUserSession :one
SELECT u.id, u.display_name, u.role, u.created_at, u.disabled_at, s.expires_at, s.max_expires_at
FROM user_sessions AS s
JOIN user_tokens AS t ON t.user_id = s.user_id AND t.token_hash = s.token_hash
JOIN users AS u ON u.id = s.user_id
WHERE s.session_hash = ?1 AND s.expires_at > ?2 AND u.disabled_at IS NULL
`

type GetUserSessionParams struct {
	SessionHash []byte
	Now         int64
}

type GetUserSessionRow struct {
	User         User
	ExpiresAt    int64
	MaxExpiresAt int64
}

// A session is valid only while its issuing token is current and access is enabled.
func (q *Queries) GetUserSession(ctx context.Context, arg GetUserSessionParams) (GetUserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSession, arg.SessionHash, arg.Now)
	var i GetUserSessionRow
	err := row.Scan(
		&i.User.ID,
		&i.User.DisplayName,
		&i.User.Role,
		&i.User.CreatedAt,
		&i.User.DisabledAt,
		&i.ExpiresAt,
		&i.MaxExpiresAt,
	)
	return i, err
}

const renewUserSession = `-- name: RenewUserSession :exec
UPDATE user_sessions SET expires_at = ? WHERE session_hash = ?
`

type RenewUserSessionParams struct {
	ExpiresAt   int64
	SessionHash []byte
}

func (q *Queries) RenewUserSession(ctx context.Context, arg RenewUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, renewUserSession, arg.ExpiresAt, arg.SessionHash)
	return err
}

const trimUserSessions = `-- name: TrimUserSessions :exec
DELETE FROM user_sessions
WHERE user_sessions.user_id = ?1 AND session_hash NOT IN (
    SELECT recent.session_hash FROM user_sessions AS recent
    WHERE recent.user_id = ?1
    ORDER BY recent.expires_at DESC, recent.rowid DESC
    LIMIT ?2
)
`

type TrimUserSessionsParams struct {
	UserID int64
	Keep   int64
}

// Keeps each person's most recently used sessions.
func (q *Queries) TrimUserSessions(ctx context.Context, arg TrimUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, trimUserSessions, arg.UserID, arg.Keep)
	return err
}
