// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package store

import (
	"context"
	"database/sql"
)

const addChallengeMovie = `-- name: AddChallengeMovie :one
INSERT INTO challenge_movies (challenge_id, movie_id, position)
VALUES (?, ?, ?)
RETURNING id, challenge_id, movie_id, position, watched_at, submission_key, viewing_service
`

type AddChallengeMovieParams struct {
	ChallengeID int64
	MovieID     int64
	Position    sql.NullInt64
}

func (q *Queries) AddChallengeMovie(ctx context.Context, arg AddChallengeMovieParams) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, addChallengeMovie, arg.ChallengeID, arg.MovieID, arg.Position)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
		&i.SubmissionKey,
		&i.ViewingService,
	)
	return i, err
}

const addUnscheduledMovie = `-- name: AddUnscheduledMovie :one
INSERT INTO challenge_movies (challenge_id, movie_id, submission_key, viewing_service)
VALUES (?, ?, ?, ?)
RETURNING id, challenge_id, movie_id, position, watched_at, submission_key, viewing_service
`

type AddUnscheduledMovieParams struct {
	ChallengeID    int64
	MovieID        int64
	SubmissionKey  sql.NullString
	ViewingService string
}

func (q *Queries) AddUnscheduledMovie(ctx context.Context, arg AddUnscheduledMovieParams) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, addUnscheduledMovie,
		arg.ChallengeID,
		arg.MovieID,
		arg.SubmissionKey,
		arg.ViewingService,
	)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
		&i.SubmissionKey,
		&i.ViewingService,
	)
	return i, err
}

const clearChallengePositions = `-- name: ClearChallengePositions :exec
UPDATE challenge_movies SET position = NULL WHERE challenge_id = ?
`

func (q *Queries) ClearChallengePositions(ctx context.Context, challengeID int64) error {
	_, err := q.db.ExecContext(ctx, clearChallengePositions, challengeID)
	return err
}

const countChallengeMovies = `-- name: CountChallengeMovies :one
SELECT count(*) FROM challenge_movies WHERE challenge_id = ?
`

func (q *Queries) CountChallengeMovies(ctx context.Context, challengeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChallengeMovies, challengeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChallengeMovie = `-- name: DeleteChallengeMovie :execrows
DELETE FROM challenge_movies
WHERE challenge_movies.id = ?1
  AND challenge_movies.challenge_id = (SELECT challenges.id FROM challenges WHERE challenges.year = ?2)
`

type DeleteChallengeMovieParams struct {
	ID   int64
	Year int64
}

// Delete only the requested year's entry; its ratings cascade automatically.
func (q *Queries) DeleteChallengeMovie(ctx context.Context, arg DeleteChallengeMovieParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChallengeMovie, arg.ID, arg.Year)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChallengeMovie = `-- name: GetChallengeMovie :one
SELECT id, challenge_id, movie_id, position, watched_at, submission_key, viewing_service FROM challenge_movies
WHERE id = ? AND challenge_id = ?
`

type GetChallengeMovieParams struct {
	ID          int64
	ChallengeID int64
}

// Both identifiers scope the lookup to one challenge entry.
func (q *Queries) GetChallengeMovie(ctx context.Context, arg GetChallengeMovieParams) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, getChallengeMovie, arg.ID, arg.ChallengeID)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
		&i.SubmissionKey,
		&i.ViewingService,
	)
	return i, err
}

const getEntryBySubmission = `-- name: GetEntryBySubmission :one
SELECT id, challenge_id, movie_id, position, watched_at, submission_key, viewing_service FROM challenge_movies WHERE submission_key = ?
`

func (q *Queries) GetEntryBySubmission(ctx context.Context, submissionKey sql.NullString) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, getEntryBySubmission, submissionKey)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
		&i.SubmissionKey,
		&i.ViewingService,
	)
	return i, err
}

const listChallengeMovies = `-- name: ListChallengeMovies :many
SELECT cm.id, cm.challenge_id, cm.movie_id, cm.position, cm.watched_at, cm.viewing_service,
       m.tmdb_id, m.title, m.release_date, m.poster_path, m.overview
FROM challenge_movies AS cm
JOIN movies AS m ON m.id = cm.movie_id
WHERE cm.challenge_id = ?
ORDER BY cm.position IS NULL, cm.position, cm.id
`

type ListChallengeMoviesRow struct {
	ID             int64
	ChallengeID    int64
	MovieID        int64
	Position       sql.NullInt64
	WatchedAt      sql.NullString
	ViewingService string
	TmdbID         int64
	Title          string
	ReleaseDate    sql.NullString
	PosterPath     sql.NullString
	Overview       sql.NullString
}

func (q *Queries) ListChallengeMovies(ctx context.Context, challengeID int64) ([]ListChallengeMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChallengeMovies, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengeMoviesRow{}
	for rows.Next() {
		var i ListChallengeMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.MovieID,
			&i.Position,
			&i.WatchedAt,
			&i.ViewingService,
			&i.TmdbID,
			&i.Title,
			&i.ReleaseDate,
			&i.PosterPath,
			&i.Overview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChallengeMovieViewingService = `-- name: SetChallengeMovieViewingService :execrows
UPDATE challenge_movies
SET viewing_service = ?1
WHERE challenge_movies.id = ?2
  AND challenge_movies.challenge_id = (SELECT challenges.id FROM challenges WHERE challenges.year = ?3)
`

type SetChallengeMovieViewingServiceParams struct {
	ViewingService string
	ID             int64
	Year           int64
}

// Scope the update to one entry in the requested year.
func (q *Queries) SetChallengeMovieViewingService(ctx context.Context, arg SetChallengeMovieViewingServiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setChallengeMovieViewingService, arg.ViewingService, arg.ID, arg.Year)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setChallengeMovieWatchedAt = `-- name: SetChallengeMovieWatchedAt :one
UPDATE challenge_movies
SET watched_at = ?1
WHERE id = ?2 AND challenge_id = ?3
RETURNING id, challenge_id, movie_id, position, watched_at, submission_key, viewing_service
`

type SetChallengeMovieWatchedAtParams struct {
	WatchedAt   sql.NullString
	ID          int64
	ChallengeID int64
}

// Pass NULL to mark an entry unwatched. Both identifiers scope the update.
func (q *Queries) SetChallengeMovieWatchedAt(ctx context.Context, arg SetChallengeMovieWatchedAtParams) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, setChallengeMovieWatchedAt, arg.WatchedAt, arg.ID, arg.ChallengeID)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
		&i.SubmissionKey,
		&i.ViewingService,
	)
	return i, err
}

const setChallengePosition = `-- name: SetChallengePosition :execrows
UPDATE challenge_movies SET position = ?1
WHERE id = ?2 AND challenge_id = ?3
`

type SetChallengePositionParams struct {
	Position    sql.NullInt64
	ID          int64
	ChallengeID int64
}

func (q *Queries) SetChallengePosition(ctx context.Context, arg SetChallengePositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setChallengePosition, arg.Position, arg.ID, arg.ChallengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
