// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package store

import (
	"context"
	"database/sql"
)

const addChallengeMovie = `-- name: AddChallengeMovie :one
INSERT INTO challenge_movies (challenge_id, movie_id, position)
VALUES (?, ?, ?)
RETURNING id, challenge_id, movie_id, position, watched_at
`

type AddChallengeMovieParams struct {
	ChallengeID int64
	MovieID     int64
	Position    int64
}

func (q *Queries) AddChallengeMovie(ctx context.Context, arg AddChallengeMovieParams) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, addChallengeMovie, arg.ChallengeID, arg.MovieID, arg.Position)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
	)
	return i, err
}

const listChallengeMovies = `-- name: ListChallengeMovies :many
SELECT cm.id, cm.challenge_id, cm.movie_id, cm.position, cm.watched_at,
       m.tmdb_id, m.title, m.release_date, m.poster_path, m.overview
FROM challenge_movies AS cm
JOIN movies AS m ON m.id = cm.movie_id
WHERE cm.challenge_id = ?
ORDER BY cm.position
`

type ListChallengeMoviesRow struct {
	ID          int64
	ChallengeID int64
	MovieID     int64
	Position    int64
	WatchedAt   sql.NullString
	TmdbID      int64
	Title       string
	ReleaseDate sql.NullString
	PosterPath  sql.NullString
	Overview    sql.NullString
}

func (q *Queries) ListChallengeMovies(ctx context.Context, challengeID int64) ([]ListChallengeMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChallengeMovies, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengeMoviesRow{}
	for rows.Next() {
		var i ListChallengeMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.MovieID,
			&i.Position,
			&i.WatchedAt,
			&i.TmdbID,
			&i.Title,
			&i.ReleaseDate,
			&i.PosterPath,
			&i.Overview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChallengeMovieWatchedAt = `-- name: SetChallengeMovieWatchedAt :one
UPDATE challenge_movies
SET watched_at = ?1
WHERE id = ?2 AND challenge_id = ?3
RETURNING id, challenge_id, movie_id, position, watched_at
`

type SetChallengeMovieWatchedAtParams struct {
	WatchedAt   sql.NullString
	ID          int64
	ChallengeID int64
}

// Pass NULL to mark an entry unwatched. Both identifiers scope the update.
func (q *Queries) SetChallengeMovieWatchedAt(ctx context.Context, arg SetChallengeMovieWatchedAtParams) (ChallengeMovie, error) {
	row := q.db.QueryRowContext(ctx, setChallengeMovieWatchedAt, arg.WatchedAt, arg.ID, arg.ChallengeID)
	var i ChallengeMovie
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.MovieID,
		&i.Position,
		&i.WatchedAt,
	)
	return i, err
}
